export default [
  {
    id: 1,
    title: 'Moviest',
    description: 'MEAN stack movie app',
    image: 'https://i.ibb.co/HDZQyGT/movie.png',
    url: 'https://github.com/ltatarev/the-moviest',
    color: 'purple',
  },
  {
    id: 2,
    title: '3 day weather',
    description: 'Weather app using OpenWeatherMapAPI',
    image: 'https://i.ibb.co/GP0C0GN/cloudy.png',
    url: 'https://github.com/ltatarev/3-day-weather',
    color: 'pink',
  },
  {
    id: 3,
    title: 'React Native to do',
    description: 'Simple to do app',
    image: 'https://i.ibb.co/KWrtPx8/to-do-list.png',
    url: 'https://github.com/ltatarev/react-native-to-do',
    color: 'blue',
  },
  {
    id: 4,
    title: 'React Native news',
    description: 'News app using newsapi.org',
    image: 'https://i.ibb.co/1TSY10f/newspaper.png',
    url: 'https://github.com/ltatarev/news-app',
    color: 'peach',
  },
  {
    id: 5,
    title: 'Electron to do',
    description: 'Simple desktop to do app',
    image: 'https://i.ibb.co/fxT2nHY/to-do.png',
    url: 'https://github.com/ltatarev/electron-to-do',
    color: 'blue',
  },
  {
    id: 6,
    title: 'Personal page',
    description: 'Landing page using GatsbyJS',
    image: 'https://i.ibb.co/t2nQmR7/laptop.png',
    url: 'https://github.com/ltatarev/ltatarev.github.io',
    color: 'purple',
  },
];
