export const projects = [
  {
    name: 'Moviest',
    emo: '🎬',
    cat: 'web',
    c: '#f6a6a6',
    d: '#e98d8d',
    kind: 'web app',
    desc: 'Browse TV shows and movies through a fast, slick interface powered by the TMDB API.',
    tags: ['Next.js', 'MongoDB', 'TMDB'],
    demo: 'https://the-moviest.vercel.app/',
    code: 'https://github.com/ltatarev/the-moviest',
  },
  {
    name: 'Translatia',
    emo: '💬',
    cat: 'web',
    c: '#8fc0f0',
    d: '#77aee6',
    kind: 'web app',
    desc: 'Edit and translate .srt subtitle files right in the browser — no upload dance required.',
    tags: ['React', 'Redux', 'Vite'],
    demo: 'https://ltatarev.github.io/translatia/',
    code: 'https://github.com/ltatarev/translatia',
  },
  {
    name: 'Knjigoteka',
    emo: '📚',
    cat: 'web',
    c: '#a6d6a0',
    d: '#8fc98a',
    kind: 'landing page',
    desc: 'An organization landing page built on a headless CMS for effortless content updates.',
    tags: ['Gatsby', 'Contentful'],
    demo: 'https://knjigoteka.club/',
    code: 'https://github.com/ltatarev/knjigoteka-web',
  },
  {
    name: 'RN Template',
    emo: '⚛️',
    cat: 'mobile',
    c: '#b0adf2',
    d: '#9a96ec',
    kind: 'starter kit',
    desc: 'A modern, opinionated template for bootstrapping a React Native app in minutes.',
    tags: ['React Native', 'Redux', 'Navigation'],
    code: 'https://github.com/ltatarev/react-native-template',
  },
  {
    name: 'Next.js Blog',
    emo: '✍️',
    cat: 'web',
    c: '#c9c6be',
    d: '#b3afa4',
    kind: 'web app',
    desc: 'A clean, colorful personal blog with internationalization baked in from the start.',
    tags: ['Next.js', 'i18n', 'Vercel'],
    demo: 'https://nextjs-blog-pi-amber.vercel.app/',
    // FLAG: the old mockup pointed this at the bare profile https://github.com/ltatarev,
    // and src/data/projects.js pointed it at the react-native-template repo. Neither looks
    // right — set the real blog repo here.
    code: 'https://github.com/ltatarev',
  },
  {
    name: 'RN To-Do',
    emo: '✅',
    cat: 'mobile',
    c: '#9ee0be',
    d: '#84d3a9',
    kind: 'mobile app',
    desc: 'Create lists and tasks in a tidy little cross-platform to-do app.',
    tags: ['React Native', 'Redux'],
    code: 'https://github.com/ltatarev/react-native-to-do',
  },
  {
    name: 'RN News',
    emo: '📰',
    cat: 'mobile',
    c: '#f5ce8a',
    d: '#eebf6f',
    kind: 'mobile app',
    desc: 'The latest headlines on the go, served up via newsapi.org.',
    tags: ['React Native', 'NewsAPI'],
    code: 'https://github.com/ltatarev/news-app',
  },
  {
    name: 'This Site',
    emo: '🌐',
    cat: 'web',
    c: '#f2aec8',
    d: '#e897b6',
    kind: 'landing page',
    desc: 'My personal landing page — the one you are looking at right now.',
    tags: ['Next.js', 'GitHub Pages'],
    code: 'https://github.com/ltatarev/ltatarev.github.io',
  },
  {
    name: 'Electron To-Do',
    emo: '⚡',
    cat: 'desktop',
    c: '#97d8e8',
    d: '#7fccdf',
    kind: 'desktop app',
    desc: 'A simple desktop to-do app built with Electron and electron-forge.',
    tags: ['Electron', 'electron-store'],
    code: 'https://github.com/ltatarev/electron-to-do',
  },
  {
    name: '3 Day Weather',
    emo: '⛅',
    cat: 'web',
    c: '#a9cef2',
    d: '#93bfec',
    kind: 'web app',
    desc: 'A simple forecast browser — my early vanilla-JS days, still holding up.',
    tags: ['HTML', 'CSS', 'JavaScript'],
    demo: 'https://ltatarev.github.io/3-day-weather/',
    code: 'https://github.com/ltatarev/3-day-weather',
  },
];

export const filters = [
  { key: 'all', label: 'All', dot: 'var(--rose)', star: true },
  { key: 'web', label: 'Web', dot: '#7fb2ef' },
  { key: 'mobile', label: 'Mobile', dot: '#9ed8b6' },
  { key: 'desktop', label: 'Desktop', dot: '#f5ce8a' },
];
